/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as MeRouteImport } from './routes/me'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as FinaleRouteImport } from './routes/finale'
import { Route as CardRouteImport } from './routes/card'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPersonalizeCardRouteImport } from './routes/api/public/personalize-card'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const FinaleRoute = FinaleRouteImport.update({
  id: '/finale',
  path: '/finale',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPersonalizeCardRoute =
  ApiPublicPersonalizeCardRouteImport.update({
    id: '/api/public/personalize-card',
    path: '/api/public/personalize-card',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/finale': typeof FinaleRoute
  '/journey': typeof JourneyRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/api/public/personalize-card': typeof ApiPublicPersonalizeCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/me'
    | '/share'
    | '/api/public/personalize-card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/me'
    | '/share'
    | '/api/public/personalize-card'
  id:
    | '__root__'
    | '/'
    | '/card'
    | '/finale'
    | '/journey'
    | '/me'
    | '/share'
    | '/api/public/personalize-card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardRoute: typeof CardRoute
  FinaleRoute: typeof FinaleRoute
  JourneyRoute: typeof JourneyRoute
  MeRoute: typeof MeRoute
  ShareRoute: typeof ShareRoute
  ApiPublicPersonalizeCardRoute: typeof ApiPublicPersonalizeCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finale': {
      id: '/finale'
      path: '/finale'
      fullPath: '/finale'
      preLoaderRoute: typeof FinaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/personalize-card': {
      id: '/api/public/personalize-card'
      path: '/api/public/personalize-card'
      fullPath: '/api/public/personalize-card'
      preLoaderRoute: typeof ApiPublicPersonalizeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardRoute: CardRoute,
  FinaleRoute: FinaleRoute,
  JourneyRoute: JourneyRoute,
  MeRoute: MeRoute,
  ShareRoute: ShareRoute,
  ApiPublicPersonalizeCardRoute: ApiPublicPersonalizeCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
