/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StageOrderRouteImport } from './routes/stage.$order'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageOrderRoute = StageOrderRouteImport.update({
  id: '/stage/$order',
  path: '/stage/$order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/stage/$order': typeof StageOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/stage/$order': typeof StageOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quest': typeof QuestRoute
  '/report': typeof ReportRoute
  '/stage/$order': typeof StageOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quest' | '/report' | '/stage/$order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quest' | '/report' | '/stage/$order'
  id: '__root__' | '/' | '/quest' | '/report' | '/stage/$order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestRoute: typeof QuestRoute
  ReportRoute: typeof ReportRoute
  StageOrderRoute: typeof StageOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$order': {
      id: '/stage/$order'
      path: '/stage/$order'
      fullPath: '/stage/$order'
      preLoaderRoute: typeof StageOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestRoute: QuestRoute,
  ReportRoute: ReportRoute,
  StageOrderRoute: StageOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
